collateral:
  nominalValueAmount: canonical_nominal_amount

real estate assets:
  address: canonical_address
  realEstateType: canonical_real_estate_type

Financials:
  net_sales: canonical_net_sales
  ebitda: canonical_ebitda
